spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/consensus
    username: bee
    password: 12345678
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ConsensusPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

logging:
  level:
    com.carmenio.consensus: DEBUG
